version: '3.8'

services:
  easy-apply-bot:
    build: .
    container_name: easy-apply-bot
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - TZ=UTC
    restart: unless-stopped 